### ISSUE TITLE
Implement Mensa seat reservation

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/THI-App#71]
The upcoming semester is planned to be held in person. It’s likely the Mensa will begin to offer dishes again and it’s also likely it will bring back its seat reservation system.

Our app should offer users to automatically reserve a seat in the Mensa. Ideally the required data is pre-filled with personal data from the THI API

TODOs for this issue:

- [x] document reservation API
- [x] implement reservation API
- [x] implement E-Mail verification UI
- [x] implement reservation UI
- [x] add a `Reserve Seat` button next to each day in the dish list
- [x] Store and re-use the `verificationEmail` and `verificationCode`
- [x] display reservation code as a QR code
- [ ] store reservations in localStorage
- [ ] list reservations
- [ ] allow reservation cancellation

**Comment by M4GNV5** [comment]
TODOs for this issue:

- [ ] add a `Reserve Seat` button next to each day in the dish list
- [ ] Store and re-use the `verificationEmail` and `verificationCode`
- [ ] display reservation code as a QR code
- [ ] store reservations in localStorage
- [ ] list reservations

**Comment by M4GNV5** [comment]
I will close this issue and add reservation listing and cancellation as new issue(s), as the current state should be enough for WiSe21/22
